#!/usr/bin/env python3
# SDL2 版の OSW 層（src/global/osw-sdl.cpp）に組み込むビットマップフォントを作る
#
#   scripts/gen-osw-fonts.py [フォントのディレクトリ] > src/include/osw-sdl-fonts.h
#
# X のコアフォント 7x14・6x10・6x12（misc-fixed、ISO8859-1）の PCF を読み、文字ごとの
# 大きさとビットマップを C の配列にする。フォントのディレクトリの既定は Debian の xfonts-base の場所
# （/usr/share/fonts/X11/misc）。misc-fixed のライセンスは "Public domain font. Share and enjoy."
import gzip
import os
import struct
import sys

FONTS = [  # (X のフォント名, PCF ファイル)
    ("7x14", "7x14-ISO8859-1.pcf.gz"),
    ("6x10", "6x10-ISO8859-1.pcf.gz"),
    ("6x12", "6x12-ISO8859-1.pcf.gz"),
]

PCF_PROPERTIES = 1 << 0
PCF_ACCELERATORS = 1 << 1
PCF_METRICS = 1 << 2
PCF_BITMAPS = 1 << 3
PCF_BDF_ENCODINGS = 1 << 5
PCF_BDF_ACCELERATORS = 1 << 8

PCF_COMPRESSED_METRICS = 0x100
PCF_BYTE_MASK = 1 << 2  # 1 なら MSB first
PCF_BIT_MASK = 1 << 3   # 1 なら MSB first


class Reader:
    def __init__(self, data, offset):
        self.data = data
        self.pos = offset
        self.fmt = struct.unpack_from("<I", data, offset)[0]  # format は常に LSB first
        self.pos += 4
        self.be = bool(self.fmt & PCF_BYTE_MASK)

    def get(self, code):
        code = (">" if self.be else "<") + code
        v = struct.unpack_from(code, self.data, self.pos)
        self.pos += struct.calcsize(code)
        return v if len(v) > 1 else v[0]


def parse(data):
    assert data[:4] == b"\x01fcp", "not a PCF file"
    count = struct.unpack_from("<I", data, 4)[0]
    tables = {}
    for i in range(count):
        t, fmt, size, off = struct.unpack_from("<IIII", data, 8 + i * 16)
        tables[t] = off

    # 文字ごとの大きさ
    r = Reader(data, tables[PCF_METRICS])
    metrics = []
    if r.fmt & PCF_COMPRESSED_METRICS:
        n = r.get("H")
        for _ in range(n):
            lsb, rsb, w, asc, desc = (r.get("B") - 0x80 for _ in range(5))
            metrics.append((lsb, rsb, w, asc, desc))
    else:
        n = r.get("I")
        for _ in range(n):
            lsb, rsb, w, asc, desc, _attr = r.get("hhhhhH")
            metrics.append((lsb, rsb, w, asc, desc))

    # ビットマップ
    r = Reader(data, tables[PCF_BITMAPS])
    nglyphs = r.get("I")
    offsets = [r.get("I") for _ in range(nglyphs)]
    sizes = [r.get("I") for _ in range(4)]
    pad = 1 << (r.fmt & 3)
    msb_bit = bool(r.fmt & PCF_BIT_MASK)
    unit = 1 << ((r.fmt >> 4) & 3)
    bits = data[r.pos:r.pos + sizes[r.fmt & 3]]
    assert unit == 1 or msb_bit == r.be, "unsupported scan unit"

    # 文字コードからグリフへ
    r = Reader(data, tables[PCF_BDF_ENCODINGS])
    min_b2, max_b2, min_b1, max_b1, default_char = r.get("HHHHH")
    assert min_b1 == 0 and max_b1 == 0, "single byte fonts only"
    encoding = {}
    for code in range(min_b2, max_b2 + 1):
        g = r.get("H")
        if g != 0xFFFF:
            encoding[code] = g

    # フォント全体の ascent と descent
    r = Reader(data, tables.get(PCF_BDF_ACCELERATORS, tables[PCF_ACCELERATORS]))
    r.get("BBBBBBBB")  # noOverlap ... padding
    font_ascent, font_descent = r.get("ii")

    def glyph_rows(g):
        lsb, rsb, w, asc, desc = metrics[g]
        width, height = rsb - lsb, asc + desc
        stride = ((width + 7) // 8 + pad - 1) // pad * pad
        rows = []
        for y in range(height):
            row = 0
            for x in range(width):
                byte = bits[offsets[g] + y * stride + x // 8]
                bit = (byte >> (7 - x % 8)) & 1 if msb_bit else (byte >> (x % 8)) & 1
                if bit:
                    row |= 1 << (15 - x)  # 左端を最上位ビットにする
            rows.append(row)
        return rows

    glyphs = {}
    for code, g in encoding.items():
        if code < 256:
            glyphs[code] = (metrics[g], glyph_rows(g))
    default = encoding.get(default_char)
    return font_ascent, font_descent, glyphs, default


def main():
    fontdir = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/X11/misc"
    out = sys.stdout
    out.write("// include/osw-sdl-fonts.h\n")
    out.write("/*\n * Built in bitmap fonts for the SDL2 OSW layer (osw-sdl.cpp).\n")
    out.write(" * Generated by scripts/gen-osw-fonts.py from the X misc-fixed\n")
    out.write(" * fonts (xfonts-base): \"Public domain font.  Share and enjoy.\"\n")
    out.write(" * Do not edit.\n */\n\n")
    out.write("#ifndef OSW_SDL_FONTS_H\n#define OSW_SDL_FONTS_H\n\n")
    out.write("typedef struct {\n\tsigned char lsb, rsb, width, ascent, descent;\n")
    out.write("\tunsigned short row_start;\t/* Index into rows, MSB is the left pixel. */\n")
    out.write("} OSWSDLGlyph;\n\n")
    out.write("typedef struct {\n\tconst char *name;\n\tint ascent, descent;\n")
    out.write("\tconst OSWSDLGlyph *glyph;\t/* 256 glyphs, width 0 if missing. */\n")
    out.write("\tconst unsigned short *rows;\n} OSWSDLFont;\n\n")
    names = []
    for name, fname in FONTS:
        with gzip.open(os.path.join(fontdir, fname)) as f:
            asc, desc, glyphs, default = parse(f.read())
        ident = "osw_sdl_font_" + name.replace("x", "x")
        rows, table = [], []
        for code in range(256):
            if code in glyphs:
                (lsb, rsb, w, a, d), r = glyphs[code]
                table.append((lsb, rsb, w, a, d, len(rows)))
                rows.extend(r)
            else:
                table.append((0, 0, 0, 0, 0, 0))
        out.write(f"/* {name}: {fname} */\n")
        out.write(f"static const unsigned short {ident}_rows[] = {{")
        for i, v in enumerate(rows):
            out.write(("\n\t" if i % 12 == 0 else " ") + f"0x{v:04x},")
        out.write("\n};\n")
        out.write(f"static const OSWSDLGlyph {ident}_glyph[256] = {{\n")
        for code, (lsb, rsb, w, a, d, start) in enumerate(table):
            out.write(f"\t{{{lsb}, {rsb}, {w}, {a}, {d}, {start}}},\t/* {code} */\n")
        out.write("};\n\n")
        names.append((name, ident, asc, desc))
    out.write("static const OSWSDLFont osw_sdl_fonts[] = {\n")
    for name, ident, asc, desc in names:
        out.write(f"\t{{\"{name}\", {asc}, {desc}, {ident}_glyph, {ident}_rows}},\n")
    out.write("};\n\n#endif /* OSW_SDL_FONTS_H */\n")


if __name__ == "__main__":
    main()
