# ########################################################################
#
#                       Makefile for Universe Editor (macOS)
#
#   Rules:
#
#	all	-- builds program.
#	install -- install program.
#	clean	-- remove object and other work files.
#
#       If no arguments are givin, the program is built by default.
#
#       Objects and the program are built in $(OBJDIR), so that they
#       do not mix with the Linux build in the same source tree.
#
#       X11 is taken from XQuartz (/opt/X11).
#


# ########################################################################
# Installation Options:
#
#   You may modify any value as needed. Change only the ones you are
#   absolutly sure that requires modification.
#
PREFIX = /usr


# ########################################################################
# Compiler Flags:
#
#   These are definations to enable or disable certain compile time
#   options. Omitting a defination turns that option off.
#
#   The syntax for each defination is:
#	-D<option>
#
#	USE_GETDENTS		Use getdents() instead of readdir().
#
#       USE_XSHM		Enable MIT X Shared Memory.
#
#       HAVE_XINERAMA		Place windows on one monitor of a multi-monitor
#				(Xinerama) screen. Requires -lXinerama.
#
#   -Wno-deprecated-declarations: the macOS SDK marks sprintf() and
#   vsprintf() deprecated, which warns at every call. Other deprecations
#   are still reported by the Linux and FreeBSD builds.
#
CFLAGS  = -DUSE_XSHM -DHAVE_XINERAMA -O2 -g -Wall -Wno-deprecated-declarations


# ########################################################################
# Dependant Libraries:
#
LIB = -lm -lX11 -lXpm -lXext -lXinerama

# Library Directories:
#
X11BASE = /opt/X11
LIB_DIR = -L$(X11BASE)/lib

# Header File Directories:
#
INC = -I$(X11BASE)/include


# ########################################################################
# Program Source and Header Files:
#
include Makefile.srclist

CPP    = c++

#   GUI=sdl builds with the SDL2 implementation of the OSW layer
#   (osw-sdl.cpp) instead of X (osw-x.cpp), in its own $(OBJDIR).
GUI = x11
ifeq ($(GUI),sdl)
OBJDIR = build-darwin-sdl
SRC := $(subst osw-x.cpp,osw-sdl.cpp,$(SRC))
CFLAGS := $(filter-out -DUSE_XSHM -DHAVE_XINERAMA,$(CFLAGS)) -DOSW_SDL $(shell pkg-config --cflags sdl2)
LIB := -lm $(shell pkg-config --libs sdl2)
INC =
LIB_DIR =
else
OBJDIR = build-darwin
endif
BIN    = $(OBJDIR)/unvedit
OBJ    = $(addprefix $(OBJDIR)/,$(SRC:.cpp=.o))

$(OBJDIR)/%.o: %.cpp
	@mkdir -p $(OBJDIR)
	$(CPP) -c $< -o $@ $(INC) $(CFLAGS)


# ########################################################################
# Build Rules:
#
$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o $(BIN) $(LIB_DIR) $(LIB)

all: $(BIN)


# ########################################################################
# Install Rules:
#
#   This rule is defined externally.
#
include Makefile.install.UNIX


# ########################################################################
# Maintainance and Misc Rules:
#
clean:
	rm -rf $(OBJDIR)


# ########################################################################
