# ########################################################################
#
#                    Makefile for XShipWars Client (macOS)
#
#   Rules:
#
#	all	-- builds program.
#	install -- install program.
#	clean	-- remove object and other work files.
#
#       If no arguments are givin, the program is built by default.
#
#       Objects and the program are built in $(OBJDIR), so that they
#       do not mix with the Linux build in the same source tree.
#
#       The GUI is drawn with SDL2 (osw-sdl.cpp). SDL2 and SDL2_mixer
#       come from Homebrew (found with pkg-config). GUI=x11 builds with
#       X from XQuartz (/opt/X11) instead.
#


# ########################################################################
# Installation Options:
#
#   You may modify any value as needed. Change only the ones you are
#   absolutly sure that requires modification.
#
PREFIX = /usr


# ########################################################################
# Compiler Flags:
#
#   These are definations to enable or disable certain compile time
#   options. Omitting a defination turns that option off.
#
#   Each argument is of the format -D<option> where <option> is
#   one of the following:
#
#	USE_GETDENTS		Use getdents() instead of readdir().
#
#       USE_XSHM		Enable MIT X Shared Memory (GUI=x11 only).
#
#       HAVE_XINERAMA		Place windows on one monitor of a multi-monitor
#				(Xinerama) screen. Requires -lXinerama
#				(GUI=x11 only).
#
#       HAVE_SDL_MIXER		Play sound effects with SDL2_mixer (sound server
#				type 4). Remove it and the SDL_* lines below to
#				build without sound.
#
#       JS_SUPPORT		Enable joystick support, read with SDL2's
#				joystick API (jsw-sdl.cpp in place of the
#				old libjsw). Needs the SDL_* lines below.
#
#   -Wno-deprecated-declarations: the macOS SDK marks sprintf() and
#   vsprintf() deprecated, which warns at every call. Other deprecations
#   are still reported by the Linux and FreeBSD builds.
#
#   GNU make 3.81 of macOS has no "VAR != cmd", so $(shell) is used.
#
SDL_CFLAGS := $(shell pkg-config --cflags SDL2_mixer)
CFLAGS = -DHAVE_SDL_MIXER -DJS_SUPPORT -O2 -g -Wall -Wno-deprecated-declarations $(SDL_CFLAGS)


# ########################################################################
# Dependant Libraries:
#
#   With GUI=x11, LIB_DIR (XQuartz) comes before SDL_LIBS, whose
#   -L/opt/homebrew/lib may hold Homebrew's own libX11.
#
SDL_LIBS := $(shell pkg-config --libs SDL2_mixer)
LIB = -lm $(SDL_LIBS)

# Library Directories:
#
X11BASE = /opt/X11
LIB_DIR =

# Header File Directories:
#
INC =


# ########################################################################
# Program Source and Header Files:
#
include Makefile.srclist

CPP    = c++

#   GUI=x11 builds with X (osw-x.cpp, XQuartz) instead of SDL2
#   (osw-sdl.cpp), in its own $(OBJDIR).
GUI = sdl
ifeq ($(GUI),x11)
OBJDIR = build-darwin-x11
CFLAGS := -DUSE_XSHM -DHAVE_XINERAMA $(CFLAGS)
LIB := -lm -lX11 -lXpm -lXext -lXinerama $(SDL_LIBS)
LIB_DIR = -L$(X11BASE)/lib
#   Before SDL_CFLAGS, which adds -I/opt/homebrew/include (where
#   Homebrew's own X11 headers may be).
INC = -I$(X11BASE)/include
else
OBJDIR = build-darwin
SRC := $(subst osw-x.cpp,osw-sdl.cpp,$(SRC))
CFLAGS += -DOSW_SDL
endif
BIN    = $(OBJDIR)/xsw
OBJ    = $(addprefix $(OBJDIR)/,$(SRC:.cpp=.o))

$(OBJDIR)/%.o: %.cpp
	@mkdir -p $(OBJDIR)
	$(CPP) -c $< -o $@ $(INC) $(CFLAGS)


# ########################################################################
# Build Rules:
#
$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o $(BIN) $(LIB_DIR) $(LIB)

all: $(BIN)


# ########################################################################
# Install Rules:
#
#   This rule is defined externally.
#
include Makefile.install.UNIX


# ########################################################################
# Maintainance and Misc Rules:
#
clean:
	rm -rf $(OBJDIR)


# ########################################################################
