# ########################################################################
#
#                  Makefile for XShipWars Client
#
#   Rules:
#
#	all	-- builds program.
#	install -- install program.
#	clean	-- remove object and other work files.
#
#       If no arguments are givin, the program is built by default.
#


# ########################################################################
# Installation Options:
#
#   You may modify any value as needed. Change only the ones you are
#   absolutly sure that requires modification.
#
PREFIX = /usr


# ########################################################################
# Compiler Flags:
#
#   These are definations to enable or disable certain compile time
#   options. Omitting a defination turns that option off.
#
#   Each argument is of the format -D<option> where <option> is
#   one of the following:
#
#	USE_GETDENTS		Use getdents() instead of readdir().
#
#       USE_XSHM		Enable MIT X Shared Memory.
#
#       HAVE_XINERAMA		Place windows on one monitor of a multi-monitor
#				(Xinerama) screen. Requires -lXinerama.
#
#       HAVE_SDL_MIXER		Play sound effects with SDL2_mixer (sound server
#				type 4). Remove it and the SDL_* lines below to
#				build without sound.
#
#       JS_SUPPORT		Enable joystick support, read with SDL2's
#				joystick API (jsw-sdl.cpp in place of the
#				old libjsw). Needs the SDL_* lines below.
#
#   Other arguments include:
#
#	-O#			Specifies the optimization level the
#				compiler is to compile at. This (attempts)
#				to improve the efficiency of the generated
#				program when it runs. Available values for
#				# are from 0 to 2 (some compilers allow
#				higher values). When in doubt, set # to 2.
#
#	-g			Compile with debugging information,
#				this is useful for determining why this
#				program (if it did) crash. However this
#				may hinder performance, so don't use
#				this option unless you are attempting
#				to debug the program.
#
SDL_CFLAGS != pkg-config --cflags SDL2_mixer
CFLAGS = -DUSE_XSHM -DHAVE_XINERAMA -DHAVE_SDL_MIXER -DJS_SUPPORT -O2 -g -Wall $(SDL_CFLAGS)


# ########################################################################
# Dependant Libraries:
#
#   These are dynamic (sometimes called shared) libraries that this
#   program is to be `linked' to.
#
#   Each argument is of the format -l<name> where <name> is the name
#   of the library. You may have to add one or more -l<name> arguments
#   to the LIB line depending on what you have set in the CFLAGS line
#   farther above.
#
SDL_LIBS != pkg-config --libs SDL2_mixer
LIB = -lm -lX11 -lXpm -lXext -lXinerama $(SDL_LIBS)

# Library Directories:
#
#   All libraries are looked for in the directories specified below.
#
#   Each argument is of the format -L<dir> where <dir> is the full
#   path to the directory.
#
LIB_DIR =

# Header File Directories:
#
#   Required header files that are not in the standard locations are
#   searched for in the directories specified below.
#
#   Each argument is of the format -I<dir> where <dir> is the full
#   path to the directory.
#
INC = -I/usr/include


# ########################################################################
# Program Source and Header Files:
#
#   Do not modify any values in this section unless you know what you
#   are doing or have been instructed to do so.
#
include Makefile.srclist

CPP  = g++
BIN = xsw
OBJ = $(SRC:.cpp=.o)
.cpp.o:
	$(CPP) -c $*.cpp $(INC) $(CFLAGS)


# ########################################################################
# SDL2 GUI (make GUI=sdl):
#
#   Builds with the SDL2 implementation of the OSW layer (osw-sdl.cpp)
#   instead of X (osw-x.cpp). For testing the SDL2 GUI that is used on
#   macOS; the X build is the default. Objects and the program go to
#   $(SDL_OBJDIR) so that they do not mix with the X build.
#
GUI = x11
ifeq ($(GUI),sdl)
SDL_OBJDIR = build-linux-sdl
SRC := $(subst osw-x.cpp,osw-sdl.cpp,$(SRC))
CFLAGS := $(filter-out -DUSE_XSHM -DHAVE_XINERAMA,$(CFLAGS)) -DOSW_SDL
LIB := -lm $(SDL_LIBS)
BIN := $(SDL_OBJDIR)/$(BIN)
OBJ := $(addprefix $(SDL_OBJDIR)/,$(SRC:.cpp=.o))

$(SDL_OBJDIR)/%.o: %.cpp
	@mkdir -p $(SDL_OBJDIR)
	$(CPP) -c $< -o $@ $(INC) $(CFLAGS)
endif


# ########################################################################
# Build Rules:
#
$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o $(BIN) $(LIB) $(LIB_DIR)

all: $(BIN)


# ########################################################################
# Install Rules:
#
#   This rule is defined externally.
#
include Makefile.install.UNIX


# ########################################################################
# Maintainance and Misc Rules:
#
clean:
	rm -f a.out core *.o
	rm -rf build-linux-sdl


# ########################################################################
