# ########################################################################
#
#                       Makefile for Monitor (macOS)
#
#   Rules:
#
#	all	-- builds program.
#	install -- install program.
#	clean	-- remove object and other work files.
#
#       If no arguments are givin, the program is built by default.
#
#       Objects and the program are built in $(OBJDIR), so that they
#       do not mix with the Linux build in the same source tree.
#
#       The GUI is drawn with SDL2 (osw-sdl.cpp) from Homebrew (found
#       with pkg-config). GUI=x11 builds with X from XQuartz (/opt/X11)
#       instead.
#


# ########################################################################
# Installation Options:
#
#   You may modify any value as needed. Change only the ones you are
#   absolutly sure that requires modification.
#
PREFIX = /usr


# ########################################################################
# Compiler Flags:
#
#   These are definations to enable or disable certain compile time
#   options. Omitting a defination turns that option off.
#
#   The syntax for each defination is:
#	-D<option>
#
#	USE_GETDENTS		Use getdents() instead of readdir().
#
#       USE_XSHM		Enable MIT X Shared Memory (GUI=x11 only).
#
#       HAVE_XINERAMA		Place windows on one monitor of a multi-monitor
#				(Xinerama) screen. Requires -lXinerama
#				(GUI=x11 only).
#
#   -Wno-deprecated-declarations: the macOS SDK marks sprintf() and
#   vsprintf() deprecated, which warns at every call. Other deprecations
#   are still reported by the Linux and FreeBSD builds.
#
CFLAGS  = -O2 -g -Wall -Wno-deprecated-declarations


# ########################################################################
# Dependant Libraries:
#
LIB = $(shell pkg-config --libs sdl2)

# Library Directories:
#
X11BASE = /opt/X11
LIB_DIR =

# Header File Directories:
#
INC =


# ########################################################################
# Program Source and Header Files:
#
include Makefile.srclist

CPP    = c++

#   GUI=x11 builds with X (osw-x.cpp, XQuartz) instead of SDL2
#   (osw-sdl.cpp), in its own $(OBJDIR).
GUI = sdl
ifeq ($(GUI),x11)
OBJDIR = build-darwin-x11
CFLAGS := -DUSE_XSHM -DHAVE_XINERAMA $(CFLAGS)
LIB := -lX11 -lXpm -lXext -lXinerama
LIB_DIR = -L$(X11BASE)/lib
#   Before SDL_CFLAGS, which adds -I/opt/homebrew/include (where
#   Homebrew's own X11 headers may be).
INC = -I$(X11BASE)/include
else
OBJDIR = build-darwin
SRC := $(subst osw-x.cpp,osw-sdl.cpp,$(SRC))
CFLAGS += $(shell pkg-config --cflags sdl2) -DOSW_SDL
endif
BIN    = $(OBJDIR)/monitor
OBJ    = $(addprefix $(OBJDIR)/,$(SRC:.cpp=.o))

$(OBJDIR)/%.o: %.cpp
	@mkdir -p $(OBJDIR)
	$(CPP) -c $< -o $@ $(INC) $(CFLAGS)


# ########################################################################
# Build Rules:
#
$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o $(BIN) $(LIB_DIR) $(LIB)

all: $(BIN)


# ########################################################################
# Install Rules:
#
#   This rule is defined externally.
#
include Makefile.install.UNIX


# ########################################################################
# Maintainance and Misc Rules:
#
clean:
	rm -rf $(OBJDIR)


# ########################################################################
